# Generated by Django 2.0.1 on 2018-01-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180114_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamreal',
            name='online',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Online'),
        ),
    ]
