# Generated by Django 2.0.1 on 2018-01-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180114_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamreal',
            name='online',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Online'),
        ),
    ]
