# Generated by Django 2.0.1 on 2018-01-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180115_2106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bejegyzes',
            table='bejegyzes',
        ),
    ]
